# Generated by Django 5.2.1 on 2025-05-27 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_foto_url_usuario_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='facultad',
            new_name='contacto1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='programa',
            new_name='contacto2',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='direccion',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='universidad',
        ),
    ]
