# Generated by Django 5.2.1 on 2025-05-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_facultad_usuario_contacto1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
