# Generated by Django 5.2.1 on 2025-05-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipoUsuario',
            field=models.CharField(blank=True, default='estandar', max_length=50, null=True),
        ),
    ]
