# Generated by Django 5.2.1 on 2025-05-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
