# Generated by Django 5.2.1 on 2025-05-28 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_prenda_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='prendas/')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='prendas.prenda')),
            ],
        ),
    ]
