# Generated by Django 5.2.1 on 2025-05-28 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0003_imagenprenda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='imagen_url',
        ),
        migrations.AddField(
            model_name='prenda',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prenda',
            name='donante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prendas_donadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
