# Generated by Django 5.2.1 on 2025-05-28 22:11

from django.db import migrations, models
import django.utils.timezone
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0004_remove_prenda_imagen_url_prenda_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prenda',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prendas_donadas', to='usuarios.usuario'),
        ),
    ]
