# Generated by Django 5.2.1 on 2025-05-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0006_alter_prenda_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_solicitud', 'En solicitud')], default='disponible', max_length=20),
        ),
    ]
