# Generated by Django 5.2.1 on 2025-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0007_prenda_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='upload_status',
            field=models.CharField(choices=[('En espera', 'En espera'), ('Cargado', 'Cargado')], default='Cargado', max_length=20),
        ),
    ]
