# Generated by Django 5.2.1 on 2025-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0008_prenda_upload_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenprenda',
            name='ruta_local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
