# Generated by Django 5.2.1 on 2025-05-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0010_prenda_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prenda',
            old_name='foto',
            new_name='foto1',
        ),
        migrations.AddField(
            model_name='prenda',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='prendas/'),
        ),
        migrations.AddField(
            model_name='prenda',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='prendas/'),
        ),
    ]
